export const airspace: Record<string, string> = {
  AA: 'Minimum altitude',
  AC: 'Class B, C, D, or E Surface Area',
  AD: 'Air defense identification zone',
  AE: 'Control area',
  AF: 'Flight information region',
  AH: 'Upper control area',
  AL: 'Minimum usable flight level',
  AN: 'Area navigation route',
  AO: 'Oceanic control area',
  AP: 'Reporting point',
  AR: 'ATS route',
  AT: 'Class B Airspace',
  AU: 'Upper flight information region',
  AV: 'Upper advisory area',
  AX: 'Intersection',
  AZ: 'Aerodrome traffic zone',
};
