export const hazardous: Record<string, string> = {
  HA: 'Braking action is',
  HB: 'Braking coefficient is',
  HC: 'Covered by compacted snow to depth of x Ft',
  HD: 'Covered by dry snow to a depth of x Ft',
  HE: 'Covered by water to a depth of x Ft',
  HF: 'Totally free of snow and ice',
  HG: 'Grass cutting in progress',
  HH: 'Hazard due to',
  HI: 'Covered by ice',
  HJ: 'Launch planned',
  HK: 'Migration in progress',
  HL: 'Snow clearance completed',
  HM: 'Marked by',
  HN: 'Covered by wet snow or slush to a depth of x Ft',
  HO: 'Obscured by snow',
  HP: 'Snow clearance in progress',
  HQ: 'Operation cancelled',
  HR: 'Standing water',
  HS: 'Sanding in progress',
  HT: 'Approach according to signal area only',
  HU: 'Launch in progress',
  HV: 'Work completed',
  HW: 'Work in progress',
  HX: 'Concentration of birds',
  HY: 'Snow banks exist',
  HZ: 'Covered by frozen ruts and ridges',
};
