export const lightingfacilities: Record<string, string> = {
  LA: 'Approach lighting system',
  LB: 'Airport beacon',
  LC: 'Runway center line lights',
  LD: 'Landing direction indicator lights',
  LE: 'Runway edge lights',
  LF: 'Sequenced flashing lights',
  LH: 'High intensity runway lights',
  LI: 'Runway end identifier lights',
  LK: 'Category II components of approach lighting system',
  LL: 'Low intensity runway lights',
  LM: 'Medium intensity runway lights',
  LP: 'Precision approach path indicator',
  LR: 'All landing area lighting facilities',
  LS: 'Stopway lights',
  LT: 'Threshold lights',
  LV: 'Visual approach slope indicator system',
  LW: 'Heliport lighting',
  LX: 'Taxiway center line lights',
  LY: 'Taxiway edge lights',
  LZ: 'Runway touchdown zone lights',
};
