export const limitations: Record<string, string> = {
  LA: 'Operating on Auxiliary Power Supply',
  LB: 'Reserved for aircraft based therein',
  LC: 'Closed',
  LD: 'Unsafe',
  LE: 'Operated without auxiliary power supply',
  LF: 'Interference from',
  LG: 'Operating without identification',
  LH: 'Unserviceable for aircraft heavier than',
  LI: 'Close to IFR operations',
  LK: 'Operating as a fixed light',
  LL: 'Usable for lenght of... and width of...',
  LN: 'Close to all night operations',
  LP: 'Prohibited to',
  LR: 'Aircraft restricted to runways and taxiways',
  LS: 'Subject to interruption',
  LT: 'Limited to',
  LV: 'Close to VFR operations',
  LW: 'Will take place',
  LX: 'Operating but caution advised to',
};
